# Generated by Django 5.2.5 on 2025-08-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
